//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMD.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMDBasicEntities : DbContext
    {
        public CMDBasicEntities()
            : base("name=CMDBasicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BAgeRecord> BAgeRecords { get; set; }
        public DbSet<BAreaRecord> BAreaRecords { get; set; }
        public DbSet<BDiseaseCategoryRecord> BDiseaseCategoryRecords { get; set; }
        public DbSet<BDiseasePropertyRecord> BDiseasePropertyRecords { get; set; }
        public DbSet<BDiseaseRecord> BDiseaseRecords { get; set; }
        public DbSet<BDosageFormsRecord> BDosageFormsRecords { get; set; }
        public DbSet<BDrugEffectCategroyRecord> BDrugEffectCategroyRecords { get; set; }
        public DbSet<BDrugEffectRecord> BDrugEffectRecords { get; set; }
        public DbSet<BDrugRecord> BDrugRecords { get; set; }
        public DbSet<BDurgTasteRecord> BDurgTasteRecords { get; set; }
        public DbSet<BDynastyRecord> BDynastyRecords { get; set; }
        public DbSet<BEnvironmentRecord> BEnvironmentRecords { get; set; }
        public DbSet<BFamousPrescriptionRecord> BFamousPrescriptionRecords { get; set; }
        public DbSet<BHerbsRecord> BHerbsRecords { get; set; }
        public DbSet<BIndicationsRecord> BIndicationsRecords { get; set; }
        public DbSet<BMeridianRecord> BMeridianRecords { get; set; }
        public DbSet<BPathogenesisRecord> BPathogenesisRecords { get; set; }
        public DbSet<BPathogenRecord> BPathogenRecords { get; set; }
        public DbSet<BSeasonRecord> BSeasonRecords { get; set; }
        public DbSet<BSexRecord> BSexRecords { get; set; }
        public DbSet<BSymptomRecord> BSymptomRecords { get; set; }
        public DbSet<BSyndromesRecord> BSyndromesRecords { get; set; }
        public DbSet<ContentRecord> ContentRecords { get; set; }
        public DbSet<DrugReferenceDetailRecord> DrugReferenceDetailRecords { get; set; }
        public DbSet<DrugReferenceRecord> DrugReferenceRecords { get; set; }
        public DbSet<MMainSourceRecord> MMainSourceRecords { get; set; }
        public DbSet<MRelationAgeRecord> MRelationAgeRecords { get; set; }
        public DbSet<MRelationDiseasePropertyRecord> MRelationDiseasePropertyRecords { get; set; }
        public DbSet<MRelationDosageRecord> MRelationDosageRecords { get; set; }
        public DbSet<MRelationDrugRecord> MRelationDrugRecords { get; set; }
        public DbSet<MRelationDynastyRecord> MRelationDynastyRecords { get; set; }
        public DbSet<MRelationEnvironmentRecord> MRelationEnvironmentRecords { get; set; }
        public DbSet<MRelationFamousPrescriptionRecord> MRelationFamousPrescriptionRecords { get; set; }
        public DbSet<MRelationPathogenesisRecord> MRelationPathogenesisRecords { get; set; }
        public DbSet<MRelationPhysiqueRecord> MRelationPhysiqueRecords { get; set; }
        public DbSet<MRelationSeasonRecord> MRelationSeasonRecords { get; set; }
        public DbSet<MRelationSexRecord> MRelationSexRecords { get; set; }
        public DbSet<MRelationSymptomRecord> MRelationSymptomRecords { get; set; }
        public DbSet<MRelationSyndromesRecord> MRelationSyndromesRecords { get; set; }
        public DbSet<MRelationTherapyRecord> MRelationTherapyRecords { get; set; }
        public DbSet<BTherapyRecord> BTherapyRecords { get; set; }
    }
}
