//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMD.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentRecord
    {
        public long Id { get; set; }
        public long DiseaseCategory_Id { get; set; }
        public long Dynasty_Id { get; set; }
        public long Disease_Id { get; set; }
        public long DiseaseProperty_Id { get; set; }
        public long Season_Id { get; set; }
        public long Environment_Id { get; set; }
        public long Age_Id { get; set; }
        public long Sex_Id { get; set; }
        public long Symptom_Id { get; set; }
        public long Syndromes_Id { get; set; }
        public long DosageForms_Id { get; set; }
        public long FamousPrescription_Id { get; set; }
        public long DrugReference_Id { get; set; }
    }
}
