//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMD.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRelationSeasonRecord
    {
        public long Id { get; set; }
        public long MainSourceId { get; set; }
        public long SeasonId { get; set; }
        public string SeasonName { get; set; }
        public bool IsActive { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
