//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMD.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRelationPhysiqueRecord
    {
        public long Id { get; set; }
        public long MainSourceId { get; set; }
        public long PhysiqueId { get; set; }
        public string PhysiqueName { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public string CreateTime { get; set; }
        public string UpdateTime { get; set; }
    }
}
